# Generated by Django 5.0.8 on 2024-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangluong',
            fields=[
                ('maluong', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manv', models.CharField(max_length=10)),
                ('sogio', models.FloatField()),
                ('luongcoban', models.FloatField()),
                ('tongluong', models.FloatField()),
            ],
            options={
                'db_table': 'bangluong',
            },
        ),
        migrations.CreateModel(
            name='Baotri',
            fields=[
                ('mabt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('matb', models.CharField(max_length=10)),
                ('ngaybt', models.DateField()),
                ('mota', models.CharField(max_length=100)),
                ('chiphi', models.FloatField()),
                ('nguoithuchien', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'baotri',
            },
        ),
        migrations.CreateModel(
            name='Dungcu',
            fields=[
                ('madc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tendc', models.CharField(max_length=50)),
                ('soluong', models.IntegerField()),
                ('dvt', models.CharField(max_length=20)),
                ('ngaymua', models.DateField()),
                ('giamua', models.FloatField()),
            ],
            options={
                'db_table': 'dungcu',
            },
        ),
        migrations.CreateModel(
            name='Nghiphep',
            fields=[
                ('manp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manv', models.CharField(max_length=10)),
                ('ngaybd', models.DateField()),
                ('ngaykt', models.DateField()),
                ('lydonghi', models.CharField(max_length=50)),
                ('trangthai', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'nghiphep',
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=10)),
                ('ngaysinh', models.DateField()),
                ('sdt', models.IntegerField()),
                ('diachi', models.CharField(max_length=70)),
                ('ngayvaolam', models.DateField()),
                ('vitricongviec', models.CharField(max_length=20)),
                ('trangthai', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nhanvien',
            },
        ),
        migrations.CreateModel(
            name='Thietbi',
            fields=[
                ('matb', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tentb', models.CharField(max_length=50)),
                ('loaitb', models.CharField(max_length=20)),
                ('soluong', models.FloatField()),
                ('tinhtrang', models.CharField(max_length=20)),
                ('ngaymua', models.DateField()),
                ('giamua', models.FloatField()),
            ],
            options={
                'db_table': 'thietbi',
            },
        ),
        migrations.CreateModel(
            name='Thongtinnguyenlieu',
            fields=[
                ('manl', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tennl', models.CharField(max_length=30)),
                ('gia', models.FloatField()),
                ('dvt', models.CharField(max_length=10)),
                ('soluong', models.FloatField()),
                ('ngayhethan', models.DateField()),
            ],
            options={
                'db_table': 'nguyenlieu',
            },
        ),
        migrations.AlterModelTable(
            name='calam',
            table='calam',
        ),
    ]
