# Generated by Django 5.1.2 on 2024-10-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bangluong_baotri_dungcu_nghiphep_nhanvien_thietbi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
            ],
        ),
    ]
