# Generated by Django 4.2 on 2024-11-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='calam',
            name='manv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nhanvien'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='hoten',
            field=models.CharField(max_length=30),
        ),
    ]
