# Generated by Django 4.0.8 on 2024-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calam',
            fields=[
                ('macalam', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manv', models.CharField(max_length=10)),
                ('ngay', models.DateField()),
                ('giobd', models.TimeField()),
                ('giokt', models.TimeField()),
            ],
        ),
    ]
